language: java
sudo: false
dist: bionic
addons:
  apt:
    packages:
      - ant
      - ant-optional
install:
  - |
      export ECLIPSE_TAR=eclipse.tar.gz
      export ECLIPSE_URL=http://ftp.snt.utwente.nl/pub/software/eclipse//eclipse/downloads/drops4/R-4.14-201912100610/eclipse-SDK-4.14-linux-gtk-x86_64.tar.gz
      wget ${ECLIPSE_URL} -O ${ECLIPSE_TAR}
      tar -C ${TRAVIS_BUILD_DIR}/.. -xzf ${ECLIPSE_TAR}
      export ECLIPSE_EXE=${TRAVIS_BUILD_DIR}/../eclipse/eclipse
script:
  - ant test
  - ant eclipseformat
  - ant checkstyle
