name: Tests

on: [push, pull_request]

jobs:
  test_som:
    runs-on: ubuntu-20.04 # ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Tests
        run: |
          ant test
      
      - name: CheckStyle
        run: |
          ant checkstyle
      
      - name: Download Eclipse
        run: |
          export ECLIPSE_TAR=eclipse.tar.gz
          export ECLIPSE_URL=https://ftp.halifax.rwth-aachen.de/eclipse/eclipse/downloads/drops4/R-4.17-202009021800/eclipse-SDK-4.17-linux-gtk-x86_64.tar.gz
          wget ${ECLIPSE_URL} -O ${ECLIPSE_TAR}
          tar -C ${GITHUB_WORKSPACE}/.. -xzf ${ECLIPSE_TAR}
          
      
      - name: Check Eclipse Format
        run: |
          export ECLIPSE_EXE=${GITHUB_WORKSPACE}/../eclipse/eclipse
          ant eclipseformat
