name: Tests

on: [push, pull_request]

jobs:
  test_som:
    runs-on: ubuntu-24.04 # ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Tests
        run: |
          ant test

      - name: SomSom Tests
        run: |
          ./som.sh -cp core-lib/Smalltalk:core-lib/TestSuite:core-lib/SomSom/src/compiler:core-lib/SomSom/src/vm:core-lib/SomSom/src/vmobjects:core-lib/SomSom/src/interpreter:core-lib/SomSom/src/primitives \
            core-lib/SomSom/tests/SomSomTests.som

      - name: CheckStyle
        run: |
          ant checkstyle

      - name: Download Eclipse
        run: |
          export ECLIPSE_TAR=eclipse.tar.gz
          export ECLIPSE_URL=https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.22-202111241800/eclipse-SDK-4.22-linux-gtk-x86_64.tar.gz
          wget ${ECLIPSE_URL} -O ${ECLIPSE_TAR}
          tar -C ${GITHUB_WORKSPACE}/.. -xzf ${ECLIPSE_TAR}

      - name: Check Eclipse Format
        run: |
          export ECLIPSE_EXE=${GITHUB_WORKSPACE}/../eclipse/eclipse
          ant eclipseformat

      - name: Checkout AWFY
        uses: actions/checkout@v4
        with:
          repository: smarr/are-we-fast-yet
          path: are-we-fast-yet

      - name: AWFY Test Run
        run: |
          pwd
          export JAVA_HOME=$JAVA_HOME_8_X64
          pip install ReBench
          rebench awfy-test.conf
